[project]
name = "toolkit"
version = "0.1.0"
description = "A collection of useful Python utilities"
authors = [{ name="Your Name", email="you@example.com" }]
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"